const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
  ADD_TO_CART: "CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
};

export default ACTIONS;
